
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BuffInfoConfig : Luban.BeanBase
{
    public BuffInfoConfig(JSONNode _buf) 
    {
        { var __json0 = _buf["NumericTypes"]; if(!__json0.IsArray) { throw new SerializationException(); } NumericTypes = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NumericTypes.Add(__v0); }   }
        { if(!_buf["BuffAddType"].IsNumber) { throw new SerializationException(); }  BuffAddType = _buf["BuffAddType"]; }
        { var __json0 = _buf["NumericValues"]; if(!__json0.IsArray) { throw new SerializationException(); } NumericValues = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NumericValues.Add(__v0); }   }
        { if(!_buf["BuffInfoTimer"].IsNumber) { throw new SerializationException(); }  BuffInfoTimer = _buf["BuffInfoTimer"]; }
        { if(!_buf["BuffActionType"].IsNumber) { throw new SerializationException(); }  BuffActionType = _buf["BuffActionType"]; }
        { if(!_buf["CycleEndType"].IsNumber) { throw new SerializationException(); }  CycleEndType = _buf["CycleEndType"]; }
        { if(!_buf["Interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["Interval"]; }
        { if(!_buf["MaxLayer"].IsNumber) { throw new SerializationException(); }  MaxLayer = _buf["MaxLayer"]; }
    }

    public static BuffInfoConfig DeserializeBuffInfoConfig(JSONNode _buf)
    {
        return new BuffInfoConfig(_buf);
    }

    /// <summary>
    /// 数值id
    /// </summary>
    public readonly System.Collections.Generic.List<int> NumericTypes;
    /// <summary>
    /// buff添加类型
    /// </summary>
    public readonly int BuffAddType;
    /// <summary>
    /// buff数值
    /// </summary>
    public readonly System.Collections.Generic.List<int> NumericValues;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int BuffInfoTimer;
    /// <summary>
    /// buff执行类型
    /// </summary>
    public readonly int BuffActionType;
    /// <summary>
    /// 周期结束
    /// </summary>
    public readonly int CycleEndType;
    /// <summary>
    /// 间隔
    /// </summary>
    public readonly int Interval;
    /// <summary>
    /// 最大层级
    /// </summary>
    public readonly int MaxLayer;
   
    public const int __ID__ = -880802205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "NumericTypes:" + Luban.StringUtil.CollectionToString(NumericTypes) + ","
        + "BuffAddType:" + BuffAddType + ","
        + "NumericValues:" + Luban.StringUtil.CollectionToString(NumericValues) + ","
        + "BuffInfoTimer:" + BuffInfoTimer + ","
        + "BuffActionType:" + BuffActionType + ","
        + "CycleEndType:" + CycleEndType + ","
        + "Interval:" + Interval + ","
        + "MaxLayer:" + MaxLayer + ","
        + "}";
    }
}

}
