
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.languageConfig
{
public partial class TbLanguageConfig
{
    private readonly System.Collections.Generic.Dictionary<int, LanguageConfig> _dataMap;
    private readonly System.Collections.Generic.List<LanguageConfig> _dataList;
    
    public TbLanguageConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LanguageConfig>();
        _dataList = new System.Collections.Generic.List<LanguageConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LanguageConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LanguageConfig.DeserializeLanguageConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LanguageConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<LanguageConfig> DataList => _dataList;

    public LanguageConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LanguageConfig Get(int key) => _dataMap[key];
    public LanguageConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

