
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LanguageConfig : Luban.BeanBase
{
    public LanguageConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["languageName"].IsString) { throw new SerializationException(); }  LanguageName = _buf["languageName"]; }
        { if(!_buf["languageType"].IsNumber) { throw new SerializationException(); }  LanguageType = _buf["languageType"]; }
        { if(!_buf["languageIcon"].IsString) { throw new SerializationException(); }  LanguageIcon = _buf["languageIcon"]; }
        { if(!_buf["languageFonts"].IsString) { throw new SerializationException(); }  LanguageFonts = _buf["languageFonts"]; }
    }

    public static LanguageConfig DeserializeLanguageConfig(JSONNode _buf)
    {
        return new LanguageConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 语言名称
    /// </summary>
    public readonly string LanguageName;
    /// <summary>
    /// 语言类型
    /// </summary>
    public readonly int LanguageType;
    /// <summary>
    /// 语言图标
    /// </summary>
    public readonly string LanguageIcon;
    /// <summary>
    /// 语言所使用的字体
    /// </summary>
    public readonly string LanguageFonts;
   
    public const int __ID__ = -1704465190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "languageName:" + LanguageName + ","
        + "languageType:" + LanguageType + ","
        + "languageIcon:" + LanguageIcon + ","
        + "languageFonts:" + LanguageFonts + ","
        + "}";
    }
}

}
