
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public buffConfig.TbBuffConfig TbBuffConfig {get; }
    public languageConfig.TbLanguageConfig TbLanguageConfig {get; }
    public unitConfig.TbUnitConfig TbUnitConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBuffConfig = new buffConfig.TbBuffConfig(loader("buffconfig_tbbuffconfig"));
        TbLanguageConfig = new languageConfig.TbLanguageConfig(loader("languageconfig_tblanguageconfig"));
        TbUnitConfig = new unitConfig.TbUnitConfig(loader("unitconfig_tbunitconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBuffConfig.ResolveRef(this);
        TbLanguageConfig.ResolveRef(this);
        TbUnitConfig.ResolveRef(this);
    }
}

}
